do not persist credentials

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -15,79 +15,81 @@ jobs:
 
         steps:
 
-            - name: Checkout code
-              uses: actions/checkout@v6
+            -   name: Checkout code
+                uses: actions/checkout@v6
+                with:
+                    persist-credentials: false
 
-            - name: Install buildx
-              uses: docker/setup-buildx-action@v4
+            -   name: Install buildx
+                uses: docker/setup-buildx-action@v4
 
-            - name: Login to DockerHub
-              uses: docker/login-action@v4
-              with:
-                  username: ${{secrets.DOCKERHUB_USERNAME}}
-                  password: ${{secrets.DOCKERHUB_PASSWORD}}
+            -   name: Login to DockerHub
+                uses: docker/login-action@v4
+                with:
+                    username: ${{secrets.DOCKERHUB_USERNAME}}
+                    password: ${{secrets.DOCKERHUB_PASSWORD}}
 
-            - name: Determine version
-              run: |
-                  input="${{ github.event.inputs.kimai_tag }}"
-                  
-                  # Determine between manual trigger and release event
-                  if [ -z "$input" ]; then
-                      echo "Using release tag: ${{ github.event.release.tag_name }}"
-                      version="${{ github.event.release.tag_name }}"
-                  else
-                      echo "Using tag provided: $input"
-                      version="$input"
-                  fi
+            -   name: Determine version
+                run: |
+                    input="${{ github.event.inputs.kimai_tag }}"
+                    
+                    # Determine between manual trigger and release event
+                    if [ -z "$input" ]; then
+                        echo "Using release tag: ${{ github.event.release.tag_name }}"
+                        version="${{ github.event.release.tag_name }}"
+                    else
+                        echo "Using tag provided: $input"
+                        version="$input"
+                    fi
+                    
+                    if [[ ! $version =~ ^2\.(0|[1-9]*)(0?)\.(0|[0-9]*)(0?)$ ]]; then
+                      echo "Invalid version number: $version"
+                      exit 1
+                    fi
+                    
+                    echo "kimai_version=$version" >> $GITHUB_ENV
 
-                  if [[ ! $version =~ ^2\.(0|[1-9]*)(0?)\.(0|[0-9]*)(0?)$ ]]; then
-                    echo "Invalid version number: $version"
-                    exit 1
-                  fi
-                  
-                  echo "kimai_version=$version" >> $GITHUB_ENV
+            -   name: Apache image
+                uses: docker/build-push-action@v6
+                with:
+                    context: .
+                    file: Dockerfile
+                    build-args: |
+                        KIMAI=${{ env.kimai_version }}
+                        BASE=apache
+                    target: prod
+                    platforms: linux/amd64,linux/arm64
+                    tags: |
+                        kimai/kimai2:stable
+                        kimai/kimai2:apache
+                        kimai/kimai2:apache-${{ env.kimai_version }}
+                    push: true
 
-            - name: FPM image
-              uses: docker/build-push-action@v6
-              with:
-                  context: .
-                  file: Dockerfile
-                  build-args: |
-                      KIMAI=${{ env.kimai_version }}
-                      BASE=fpm
-                  target: prod
-                  platforms: linux/amd64,linux/arm64
-                  tags: |
-                      kimai/kimai2:latest
-                      kimai/kimai2:fpm
-                  push: true
+            -   name: FPM image
+                uses: docker/build-push-action@v6
+                with:
+                    context: .
+                    file: Dockerfile
+                    build-args: |
+                        KIMAI=${{ env.kimai_version }}
+                        BASE=fpm
+                    target: prod
+                    platforms: linux/amd64,linux/arm64
+                    tags: |
+                        kimai/kimai2:latest
+                        kimai/kimai2:fpm
+                    push: true
 
-            - name: Apache image
-              uses: docker/build-push-action@v6
-              with:
-                  context: .
-                  file: Dockerfile
-                  build-args: |
-                      KIMAI=${{ env.kimai_version }}
-                      BASE=apache
-                  target: prod
-                  platforms: linux/amd64,linux/arm64
-                  tags: |
-                      kimai/kimai2:stable
-                      kimai/kimai2:apache
-                      kimai/kimai2:apache-${{ env.kimai_version }}
-                  push: true
-
-            - name: Development image
-              uses: docker/build-push-action@v6
-              with:
-                  context: .
-                  file: Dockerfile
-                  build-args: |
-                      KIMAI=${{ env.kimai_version }}
-                      BASE=apache
-                  target: dev
-                  platforms: linux/amd64,linux/arm64
-                  tags: |
-                      kimai/kimai2:dev
-                  push: true
+            -   name: Development image
+                uses: docker/build-push-action@v6
+                with:
+                    context: .
+                    file: Dockerfile
+                    build-args: |
+                        KIMAI=${{ env.kimai_version }}
+                        BASE=apache
+                    target: dev
+                    platforms: linux/amd64,linux/arm64
+                    tags: |
+                        kimai/kimai2:dev
+                    push: true
